image: node:latest
stages:
  - test
  - build

cache:
  paths:
    - node_modules/

test and lint:
  stage: test
  script:
    - npm i
    - npm run lint
    - npm run tsc
    - npm run test:ci

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
