
version: "3.7"

volumes:
  db-data:

services:

  frontend:
    depends_on:
      - api
      - db
    build:
      context: ./bloxz-master/
    image: bloxz:1.0
    ports:
      - "80:80"

  backend:
    build:
      context: ./bloxz-backend-master/
    image: bloxz-api:1.0
    ports: 
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
      
  db:
    image: postgres:10.10
    environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "root"
          POSTGRES_DB: "bloxz"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data