version: "3"

services:
  app1:
    build:
      context: ../bloxz-master/
    ports:
      - "3001:80"

  app2:
    build:
      context: ../bloxz-master/
    ports:
      - "3002:80"

  nginx:
    build:
      context: ./
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
